language: node_js
node_js:
  - 6

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache

install:
  - yarn

script:
  - yarn run test
